image: circleci/php:7.2-stretch-node

stages:
  - test
  - deploy

variables:
  NOW_PROJECT: $CI_PROJECT_NAME

cache:
  key: "$CI_JOB_NAME"
  paths:
    - vendor

frontools:
  stage: test
  variables:
    THEME_PATH: "vendor/snowdog/theme-frontend-alpaca"
    CONFIG_PATH: "vendor/snowdog/module-alpaca-frontools/config"
  before_script:
    - mkdir -p $THEME_PATH
    - rsync -r --delete --exclude '/vendor' . $THEME_PATH
    - composer config minimum-stability dev
    - composer config prefer-stable true
    - composer config repositories.snowdog composer https://repo.snowdog.pro/
    - composer config repositories.magento composer https://repo.magento.com/
    - composer update --no-dev --no-interaction --prefer-dist --no-progress --ignore-platform-reqs
    - mkdir -p dev/tools/frontools
    - cp -r $CONFIG_PATH dev/tools/frontools
    - cd vendor/snowdog/frontools
    - yarn
    - yarn setup
  script:
    - yarn inheritance --theme alpaca
    - yarn sasslint --theme alpaca --ci
    - yarn styles --theme alpaca --ci --pipeline
    - yarn csslint --theme alpaca --ci

php-static-review:
  stage: test
  only:
    - develop
    - /^feature/.*$/
  before_script:
    - composer init --no-interaction
    - composer config repositories.snowdog composer https://repo.snowdog.pro --no-interaction
    - composer require snowdog/php-static-review --no-interaction --no-progress --prefer-dist
    - export PACKAGE_DIR="vendor/snowdog/php-static-review"
    - export MAGENTO_VERSION="magento2"
    - if [[ $CI_COMMIT_REF_NAME == "develop" ]]; then export BRANCH="master"; fi
    - if [[ $CI_COMMIT_REF_NAME == feature* ]]; then export BRANCH="develop"; fi
  script:
    - vendor/bin/ci.sh $BRANCH "$CI_COMMIT_REF_NAME" "$PACKAGE_DIR/resources/$MAGENTO_VERSION/phpcs.xml" "$PACKAGE_DIR/resources/$MAGENTO_VERSION/phpmd.xml"

components:
  stage: deploy
  variables:
    NOW_URL: https://${CI_PROJECT_NAME}-${CI_BUILD_REF_SLUG}.now.sh
  before_script:
    - cd Snowdog_Components
    - yarn
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@lab.snowdog.pro/internal/now-deployment.git
    - chmod +x now-deployment/now-deploy.sh
    - . ./now-deployment/now-deploy.sh
  script:
    - deploy
  environment:
    name: review/$CI_BUILD_REF_SLUG
    url: $NOW_URL
    on_stop: stop_review
  only:
    - branches
  except:
    - master

production:
  stage: deploy
  variables:
    NOW_URL: https://${CI_PROJECT_NAME}.now.sh
  before_script:
    - cd Snowdog_Components
    - yarn
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@lab.snowdog.pro/internal/now-deployment.git
    - chmod +x now-deployment/now-deploy.sh
    - . ./now-deployment/now-deploy.sh
  script:
    - deploy
  environment:
    name: production
    url: $NOW_URL
  only:
    - master

stop_review:
  stage: deploy
  variables:
    NOW_URL: https://${CI_PROJECT_NAME}-${CI_BUILD_REF_SLUG}.now.sh
  before_script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@lab.snowdog.pro/internal/now-deployment.git
    - chmod +x now-deployment/now-deploy.sh
    - . ./now-deployment/now-deploy.sh
  script:
    - stop
  when: manual
  environment:
    name: review/$CI_BUILD_REF_SLUG
    action: stop
  only:
    - branches
  except:
    - master
