image: circleci/php:7.1-stretch-node

stages:
  - test
  - deploy

variables:
  NOW_PROJECT: $CI_PROJECT_NAME
  COMPONENTS_PATH: "vendor/snowdog/theme-frontend-colibri/Snowdog_Components"
  THEME_PATH: "vendor/snowdog/theme-frontend-colibri"

before_script:
  - cd Snowdog_Components
  - yarn
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@lab.snowdog.pro/internal/now-deployment.git
  - chmod +x now-deployment/now-deploy.sh
  - . ./now-deployment/now-deploy.sh

production:
  stage: deploy
  variables:
    NOW_URL: https://${CI_PROJECT_NAME}.now.sh
  script:
    - deploy
  environment:
    name: production
    url: $NOW_URL
  only:
    - master

lints:
  stage: test
  variables:
    NOW_URL: https://${CI_PROJECT_NAME}.now.sh
  script:
    - yarn now-build

review:
  stage: deploy
  variables:
    NOW_URL: https://${CI_PROJECT_NAME}-${CI_BUILD_REF_SLUG}.now.sh
  script:
    - deploy
  environment:
    name: review/$CI_BUILD_REF_SLUG
    url: $NOW_URL
    on_stop: stop_review
  only:
    - branches
  except:
    - master

stop_review:
  stage: deploy
  variables:
    NOW_URL: https://${CI_PROJECT_NAME}-${CI_BUILD_REF_SLUG}.now.sh
  script:
    - stop
  when: manual
  environment:
    name: review/$CI_BUILD_REF_SLUG
    action: stop
  only:
    - branches
  except:
    - master
